---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-headless
  namespace: state-as576-220250-v23
  labels:
    app: postgres
    org.bstu.course: "RSIOT"
    org.bstu.student.id: "220250"
    org.bstu.group: "AS-576"
    org.bstu.variant: "23"
    org.bstu.owner: "Danik-oss"
    org.bstu.student.slug: "as-576-220250-v23"
  annotations:
    org.bstu.student.fullname: "Черешко Даниил Николаевич"
spec:
  clusterIP: None  # Headless Service для стабильных DNS имён
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
