version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rsiot-v23:stu-220250-v23
    container_name: app-as-576-220250-v23
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9043:9043"
    environment:
      STU_ID: "220250"
      STU_GROUP: "as-576"
      STU_VARIANT: "23"
      APP_PORT: "9043"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_KEY_PREFIX: "stu:220250:v23"
    labels:
      org.bstu.owner: "Danik-oss"
      org.bstu.student.slug: "as-576-220250-v23"
    networks:
      - net-as-576-220250-v23

  redis:
    image: redis:7-alpine
    container_name: redis-as-576-220250-v23
    volumes:
      - data_w23:/data
    labels:
      org.bstu.owner: "Danik-oss"
      org.bstu.student.slug: "as-576-220250-v23"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-as-576-220250-v23

volumes:
  data_w23:
    name: data_w23

networks:
  net-as-576-220250-v23:
    name: net-as-576-220250-v23
