apiVersion: v1
kind: ConfigMap
metadata:
  name: app23-config
  namespace: web23
  labels:
    app: app23
    org.bstu.student.fullname: "Черешко Даниил Николаевич"
    org.bstu.student.id: "220250"
    org.bstu.group: "AS-576"
    org.bstu.variant: "23"
    org.bstu.course: "RSIOT"
data:
  APP_NAME: "RSIOT App 23"
  APP_ENV: "production"
